language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - debianutils
    - libpcre3-dev
    - m4
    - perl
    - pkg-config
    - tzdata
cache:
  directories:
    - $HOME/.opam
env:
  global:
  - PINS="hello:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="hello" OCAML_VERSION="4.02"
  - PACKAGE="hello" OCAML_VERSION="4.03"
  - PACKAGE="hello" OCAML_VERSION="4.04"
  - PACKAGE="hello" OCAML_VERSION="4.05"
  - PACKAGE="hello" OCAML_VERSION="4.06"

