language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
- globals:
  - PINS="hello:."
- matrix:
  - PACKAGE=hello OCAML_VERSION=4.01
  - PACKAGE=hello OCAML_VERSION=4.02
  - PACKAGE=hello OCAML_VERSION=4.03
  - PACKAGE=hello OCAML_VERSION=4.04
  - PACKAGE=hello OCAML_VERSION=4.05
  - PACKAGE=hello OCAML_VERSION=4.06

